[package]
name = "rustream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m3u = {git = "https://github.com/shnorbluk/m3u", branch = "iptv", features = ["iptv"]}
#m3u = {path = "../m3u", features=["iptv"]}